# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                 FUNCTIONS                                  │
# └────────────────────────────────────────────────────────────────────────────┘

[functions.classify_intent]
type = "json"
output_schema = "functions/classify_intent/output_schema.json"

[functions.classify_intent.variants.gpt_4o]
type = "chat_completion"
model = "openai::gpt-4o-2024-08-06"
system_template = "functions/classify_intent/prompts/system_template.minijinja"
json_mode = "strict"
weight = 0

[functions.classify_intent.variants.gpt_4o_mini]
type = "chat_completion"
model = "openai::gpt-4o-mini-2024-07-18"
system_template = "functions/classify_intent/prompts/system_template.minijinja"
json_mode = "strict"
weight = 0

[functions.classify_intent.variants.gpt_4o_mini_dicl]
type = "experimental_dynamic_in_context_learning"
embedding_model = "text-embedding-3-small"
model = "openai::gpt-4o-mini-2024-07-18"
k = 5
system_instructions = "functions/classify_intent/prompts/system_template.minijinja"
json_mode = "strict"
weight = 1

[functions.generate_response]
type = "json"
output_schema = "functions/generate_response/output_schema.json"

[functions.generate_response.variants.gpt_4o]
type = "chat_completion"
model = "openai::gpt-4o-2024-08-06"
system_template = "functions/generate_response/prompts/system_template.minijinja"
json_mode = "strict"
weight = 0

[functions.generate_response.variants.gpt_4o_mini]
type = "chat_completion"
model = "openai::gpt-4o-mini-2024-07-18"
system_template = "functions/generate_response/prompts/system_template.minijinja"
json_mode = "strict"
weight = 0

[functions.generate_response.variants.gpt_4o_mini_dicl]
type = "experimental_dynamic_in_context_learning"
embedding_model = "text-embedding-3-small"
model = "openai::gpt-4o-mini-2024-07-18"
k = 10
system_instructions = "functions/generate_response/prompts/system_template.minijinja"
json_mode = "strict"
weight = 1

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                  METRICS                                   │
# └────────────────────────────────────────────────────────────────────────────┘

[metrics.intent_accuracy]
type = "boolean"
level = "inference"
optimize = "max"

[metrics.response_relevance]
type = "float"
level = "inference"
optimize = "max"

[metrics.resolution_potential]
type = "boolean"
level = "episode"
optimize = "max"

[metrics.customer_satisfaction]
type = "float"
level = "episode"
optimize = "max"

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                            EMBEDDING MODELS                                │
# └────────────────────────────────────────────────────────────────────────────┘

[embedding_models."text-embedding-3-small"]
routing = ["openai"]

[embedding_models."text-embedding-3-small".providers.openai]
type = "openai"
model_name = "text-embedding-3-small"